name: Manual Test - Analyze and Generate

on:
  workflow_dispatch:  # 手動で実行できるようにするトリガー

jobs:
  generate_test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai tweepy

      - name: Run Analyzer and Generator (Test)
        run: python tweet_bot/analyze_and_generate.py
      
      - name: Upload generated tweet as artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: generated-tweet         # ← Artifact の名前
          path: saved/                  # ← 保存したフォルダのパス
